export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAILED = "LOGIN_ACCOUNT_FAILED";

export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";

export const SIGUP_ACCOUNT = "SIGUP_ACCOUNT";
export const SIGUP_ACCOUNT_SUCCESS = "SIGUP_ACCOUNT_SUCCESS";
export const SIGUP_ACCOUNT_FAILED = "SIGUP_ACCOUNT_FAILED";

export const RESET_FLAGS = "RESET_FLAGS"; 


