export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAILED = "LOGIN_ACCOUNT_FAILED";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
